server:
  port: 8080

frog:
  database:
    name: ep-data

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

logging:
  level:
    root: WARN
    fr.frogdevelopment: INFO
    org.atmosphere: WARN


# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false

