server:
  port: 8080

frog:
  database:
    name: ep-data

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

logging:
  level:
    root: WARN
    fr.frogdevelopment: INFO
    org.atmosphere: WARN


vaadin:
  whitelisted-packages: fr/frogdevelopment/ep/views
  servlet:
    productionMode: true

