name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Setup Java environment based on AdoptOpenJDK
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: openjdk11
          openjdk_impl: openj9
      #          release: jdk-11.0.5+10
      - name: Compile
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test -x bootBuildInfo
#      - name: Containerize
#        run: ./gradlew jib -Djib.to.auth.username=${{ secrets.DOCKER_USR }} -Djib.to.auth.password=${{ secrets.DOCKER_PSW }} -Djib.to.tags=${BRANCH_NAME} -Djib.console='plain' -x bootBuildInfo

